@Gateway_HostAddress = http://localhost:5058

GET {{Gateway_HostAddress}}/health
Accept: application/json

###

GET {{Gateway_HostAddress}}/liveness
Accept: application/json

###

POST {{Gateway_HostAddress}}/api/v1/mq
Content-Type: application/json

{
    "Topic": "topic",
    "Payload": "payload"
}