@ApiGateway_HostAddress = http://localhost:5058

GET {{ApiGateway_HostAddress}}/health
Accept: application/json

###

GET {{ApiGateway_HostAddress}}/liveness
Accept: application/json

###

POST {{ApiGateway_HostAddress}}/api/v1/mq
Content-Type: application/json
X-Tenant-Id: "Default"

{
    "Topic": "topic",
    "Payload": "payload"
}