@IdentityProviderAPI_HostAddress = http://localhost:51004

GET {{IdentityProviderAPI_HostAddress}}/health
Accept: application/json

###

GET {{IdentityProviderAPI_HostAddress}}/liveness
Accept: application/json

###

GET {{IdentityProviderAPI_HostAddress}}/auth/token
Accept: application/json

###