name: "Build and Test"
description: "Build and Test"

inputs:
  dotnet-version:
    description: "The version of .NET to use"
    required: true
  dotnet-quality:
    description: "The quality of .NET to use"
    required: false
    default: "stable"
  project_path:
    description: "Project path"
    required: true
  tests_path:
    description: "Tests path"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Build"
      uses: ./.github/workflows/composite/build
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}
        project_path: ${{ inputs.project_path }}
    - name: "Test"
      uses: ./.github/workflows/composite/test
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}
        tests_path: ${{ inputs.tests_path }}