@Gateway.API_HostAddress = http://localhost:5058

GET {{Gateway.API_HostAddress}}/health
Accept: application/json

###

GET {{Gateway.API_HostAddress}}/liveness
Accept: application/json

###

POST {{Gateway.API_HostAddress}}/api/v1/mq
Content-Type: application/json

{
    "Topic": "topic",
    "Payload": "payload"
}

###