@url = http://localhost:51001

GET {{url}}/health
Accept: application/json

###

GET {{url}}/liveness
Accept: application/json

###

POST {{url}}/api/v1/mq
Content-Type: application/json

{
    "Topic": "topic",
    "Payload": "payload"
}

###