@url = http://localhost:51005

###

GET {{url}}/health
Content-Type: application/json

###

GET {{url}}/liveness
Content-Type: application/json

###

GET {{url}}/org?orgTypeId=1&offset=0&limit=10
Content-Type: application/json

###

GET {{url}}/org/1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

PUT {{url}}/org?oid=1.2.643.5.1.13.13.12.2.78.6258
Content-Type: application/json

{
    "oid": "1.2.643.5.1.13.13.12.2.78.6258",
    "headOid": null,
    "nameFull": "Частное учреждение образовательная организация высшего образования «Медицинский университет «Реавиз»",
    "nameShort": "Медицинский Университет «Реавиз»",
    "inn": "6317006620",
    "kpp": "631501001",
    "ogrn": "1026301420716",
    "ogrnDate": "2022-03-01T00:00:00Z",
    "legalAddress": {
      "id": 0,
      "aoidArea": "a0548913-da5c-4732-a421-2251d9aed895",
      "aoidStreet": "2fea8389-c6ff-4844-9ec1-67bd10061174",
      "houseid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
      "houseguid": null,
      "GARguid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
      "region": {
        "id": 1,
        "region": "Республика Адыгея (Адыгея)",
        "territoryCode": 1,
        "isFederalCity": false
      },
      "areaName": "Абадзехское",
      "prefixArea": "с/п",
      "streetName": "Песчаная",
      "prefixStreet": "ул",
      "house": "10",
      "building": null,
      "struct": null,
      "flat": null
    },
    "orgType": {
      "code": 1,
      "name": "Государственное юридическое лицо"
    },
    "structure": [],
    "lands": [],
    "parkingArea": 0,
    "certSeries": "12",
    "certNumber": "123456789",
    "certDate": "2022-03-01T00:00:00Z",
    "regOrgName": "Налоговый орган",
    "regDate": "2022-03-01T00:00:00Z",
    "regOrg": "Налоговый орган",
    "regOrgAddress": {
      "id": 0,
      "aoidArea": "bb035cc3-1dc2-4627-9d25-a1bf2d4b936b",
      "aoidStreet": "8bb0d86a-b5d8-4387-ae1b-4a053a6d0760",
      "houseid": "31d1a219-2f5f-4cb9-92e8-9dbace2a668f",
      "houseguid": null,
      "GARguid": "31d1a219-2f5f-4cb9-92e8-9dbace2a668f",
      "region": {
        "id": 63,
        "region": "Самарская область",
        "territoryCode": 63,
        "isFederalCity": false
      },
      "areaName": "Самара",
      "prefixArea": "г",
      "streetName": "Садовая",
      "prefixStreet": "ул",
      "house": "5",
      "building": null,
      "struct": null,
      "flat": null
    },
    "lawFormNameFull": null,
    "moDeptId": {
      "id": 1320705,
      "parentId": 1320700,
      "nameFull": "Федеральная служба по надзору в сфере здравоохранения",
      "nameShort": "Росздравнадзор",
      "isActive": true
    },
    "okopfId": null,
    "founder": null,
    "moAddress": {
      "address": {
        "id": 0,
        "aoidArea": "a0548913-da5c-4732-a421-2251d9aed895",
        "aoidStreet": "2fea8389-c6ff-4844-9ec1-67bd10061174",
        "houseid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
        "houseguid": null,
        "GARguid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
        "region": {
          "id": 1,
          "region": "Республика Адыгея (Адыгея)",
          "territoryCode": 1,
          "isFederalCity": false
        },
        "areaName": "Абадзехское",
        "prefixArea": "с/п",
        "streetName": "Песчаная",
        "prefixStreet": "ул",
        "house": "10",
        "building": null,
        "struct": null,
        "flat": null
      },
      "addrRegion": {
        "code": 1,
        "name": "Республика Адыгея (Адыгея)"
      },
      "cadastralNumber": "12:31:2312312:31",
      "latitude": 44.429867,
      "longitude": 40.252975,
      "postIndex": "123456"
    },
    "deleteDate": "2022-06-27T00:00:00Z",
    "deleteReason": {
      "id": 2,
      "deleteReason": "Дубль карточки МО"
    },
    "regionId": {
      "id": 63,
      "region": "Самарская область",
      "territoryCode": 63,
      "isFederalCity": false
    },
    "medicalSubjectId": [
      {
        "id": 2,
        "medicalSubject": "Медицинская организация"
      }
    ],
    "oldOid": null,
    "moAgencyKindId": {
      "id": 1,
      "parentId": 0,
      "agencyKind": "Больница (в том числе детская)"
    },
    "moAgencyProfileId": null,
    "moTerritoryId": {
      "id": 6,
      "parentId": null
    },
    "moLevelId": {
      "id": 1,
      "moLevel": "I уровень"
    },
    "eoOrganizationType": null,
    "email": "test@test.1.test.ru",
    "site": null,
    "attachedPeople": 0,
    "medicalInformationSystem": false,
    "routingOKS": null,
    "routingNumber": null,
    "primaryVascular": false,
    "medicalAidForm": [],
    "medicalAidCondition": null,
    "maxServiceDistance": 0,
    "mark": null
  }

###

DELETE {{url}}/org?oid=1.2.643.5.1.13.13.12.2.78.6258&deleteReason=1
Content-Type: application/json

###

GET {{url}}/org/depart?departTypeId=1&oid=1.2.643.5.1.13.13.12.2.31.2855&offset=0&limit=10
Content-Type: application/json

###

GET {{url}}/org/depart/1.2.643.5.1.13.13.12.2.31.2855.0.385565?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

POST {{url}}/org/depart?oid=1.2.643.5.1.13.13.12.2.77.7799
Content-Type: application/json

{
  "departName": "Отделение №1",
  "departStructure": {
    "level": "1",
    "headDepart": "",
  },
  "isPlaned": false
}

###

PUT {{url}}/org/depart?oid=1.2.643.5.1.13.13.12.2.77.7799&entityId=1.2.643.5.1.13.13.12.2.77.7799
Content-Type: application/json

{
  "departName": "Отделение №1",
  "departStructure": {
    "level": "1",
    "headDepart": ""
  },
  "isPlaned": false
}

###

DELETE {{url}}/org/depart?oid=1.2.643.5.1.13.13.12.2.77.7799&entityId=1.2.643.5.1.13.13.12.2.77.7799
Content-Type: application/json

###

GET {{url}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{url}}/org/building/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=47120289-197c-4c8a-b6e4-3806c72bab75
Content-Type: application/json

###

POST {{url}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "rent": false,
  "ownageDocuments": null,
  "lawSubject": null,
  "lawType": null,
  "lawObject": null,
  "cadastralNumber": null,
  "encumbrances": null,
  "lawDescription": null,
  "rentDocuments": null,
  "regDate": null,
  "regNumber": null,
  "landlord": null,
  "renter": null,
  "tenancy": null,
  "capacityVisitors": null,
  "capacityBeds": null,
  "capacityHospital": null,
  "buildName": "Гараж",
  "buildYear": 2023,
  "beginDate": "2023-11-20T00:00:00Z",
  "liquidationDate": null,
  "liquidationReasonId": null,
  "floorCount": 1,
  "hasTrouble": false,
  "troubleDocument": null,
  "buildingPlan": null,
  "cardiologicalDepartments": null,
  "fundament": null,
  "fundamentDescription": null,
  "supportingStructures": null,
  "roofCovering": null,
  "roofCoveringDescription": null,
  "wallsMaterial": null,
  "wallsMaterialDescription": null,
  "ceilingMaterial": null,
  "ceilingMaterialDescription": null,
  "buildingSize": null,
  "rightToUse": null,
  "rightToUseDescription": null,
  "isAdapted": false,
  "isAccesibleEnv": null,
  "isHistorical": false,
  "isWeb": false,
  "buildingArea": 30,
  "builtUpArea": 30,
  "starCost": null,
  "depreciationCost": null,
  "deprecationFactor": null,
  "lastTechnicalSurveyYear": null,
  "lastTechnicalSurveyAct": null,
  "reconstructionYear": null,
  "reconstructionArea": null,
  "troubleActDetails": null,
  "needDestruction": false,
  "destructionDocument": [],
  "destructionDocumentDate": null,
  "destructionDocumentNumber": null,
  "needReconstruction": false,
  "requiredReconstructionArea": null,
  "needRepair": false,
  "repairDocument": [],
  "repairDocumentDate": null,
  "repairDocumentNumber": null,
  "objectTarget": null,
  "objectType": null,
  "floors": [],
  "workPeriod": [],
  "buildingAddress": {
    "addrRegion": "Белгородская область",
    "postIndex": "308007",
    "address": {
      "id": 0,
      "aoidArea": null,
      "aoidStreet": null,
      "houseid": null,
      "houseguid": null,
      "GARguid": "287ef30b-4a63-47f8-be8a-0876c57ab354",
      "region": {
        "id": 31,
        "region": "Белгородская область",
        "territoryCode": 31,
        "isFederalCity": false
      },
      "areaName": "Белгород",
      "prefixArea": null,
      "streetName": "Гагарина",
      "prefixStreet": null,
      "house": "гараж",
      "building": null,
      "struct": null,
      "flat": null
    },
    "cadastralNumber": null,
    "latitude": 50.618652,
    "longitude": 36.580746
  },
  "moTerritorialDepartId": "d344c071-a8d1-4a1b-95b1-7be88dfff906",
  "moTerritorialDepartName": "Кардиохирургический центр"
}

###

PUT {{url}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=47120289-197c-4c8a-b6e4-3806c72bab75
Content-Type: application/json

{
  "rent": false,
  "ownageDocuments": null,
  "lawSubject": null,
  "lawType": null,
  "lawObject": null,
  "cadastralNumber": null,
  "encumbrances": null,
  "lawDescription": null,
  "rentDocuments": null,
  "regDate": null,
  "regNumber": null,
  "landlord": null,
  "renter": null,
  "tenancy": null,
  "capacityVisitors": null,
  "capacityBeds": null,
  "capacityHospital": null,
  "buildName": "Гараж",
  "buildYear": 2023,
  "beginDate": "2023-11-20T00:00:00Z",
  "liquidationDate": null,
  "liquidationReasonId": null,
  "floorCount": 2,
  "hasTrouble": false,
  "troubleDocument": null,
  "buildingPlan": null,
  "cardiologicalDepartments": null,
  "fundament": null,
  "fundamentDescription": null,
  "supportingStructures": null,
  "roofCovering": null,
  "roofCoveringDescription": null,
  "wallsMaterial": null,
  "wallsMaterialDescription": null,
  "ceilingMaterial": null,
  "ceilingMaterialDescription": null,
  "buildingSize": null,
  "rightToUse": null,
  "rightToUseDescription": null,
  "isAdapted": false,
  "isAccesibleEnv": null,
  "isHistorical": false,
  "isWeb": false,
  "buildingArea": 30,
  "builtUpArea": 30,
  "starCost": null,
  "depreciationCost": null,
  "deprecationFactor": null,
  "lastTechnicalSurveyYear": null,
  "lastTechnicalSurveyAct": null,
  "reconstructionYear": null,
  "reconstructionArea": null,
  "troubleActDetails": null,
  "needDestruction": false,
  "destructionDocument": [],
  "destructionDocumentDate": null,
  "destructionDocumentNumber": null,
  "needReconstruction": false,
  "requiredReconstructionArea": null,
  "needRepair": false,
  "repairDocument": [],
  "repairDocumentDate": null,
  "repairDocumentNumber": null,
  "objectTarget": null,
  "objectType": null,
  "floors": [],
  "workPeriod": [],
  "buildingAddress": {
    "addrRegion": "Белгородская область",
    "postIndex": "308007",
    "address": {
      "id": 0,
      "aoidArea": null,
      "aoidStreet": null,
      "houseid": null,
      "houseguid": null,
      "GARguid": "287ef30b-4a63-47f8-be8a-0876c57ab354",
      "region": {
        "id": 31,
        "region": "Белгородская область",
        "territoryCode": 31,
        "isFederalCity": false
      },
      "areaName": "Белгород",
      "prefixArea": null,
      "streetName": "Гагарина",
      "prefixStreet": null,
      "house": "гараж",
      "building": null,
      "struct": null,
      "flat": null
    },
    "cadastralNumber": null,
    "latitude": 50.618652,
    "longitude": 36.580746
  },
  //"moTerritorialDepartId": "d344c071-a8d1-4a1b-95b1-7be88dfff906",
  //"moTerritorialDepartName": "Кардиохирургический центр"
}

###

DELETE {{url}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=47120289-197c-4c8a-b6e4-3806c72bab75
Content-Type: application/json

###

GET {{url}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{url}}/org/staff/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

POST {{url}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "staffNum": "20231121",
  "staffCreateDate": "2023-11-21T00:00:00Z",
  "beginDate": "2023-11-21T00:00:00Z",
  "endDate": "2023-11-22T00:00:00Z",
  "staffDetails": [
    {
      "nrPmuDepartId": "1.2.643.5.1.13.13.12.2.31.2855.0.181337",
      "departName": "Централизованная стерилизационная",
      "nrPmuDepartHospitalSubdivisionId": null,
      "hospitalName": null,
      "postFedCode": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "post": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "flCount": 0,
      "averageAge": null,
      "rate": 22.5,
      "busyRate": 0,
      "busyRateMain": 0,
      "externalRate": 0,
      "vacancy": 22.5,
      "staffNote": null
    }
  ]
}

###

PUT {{url}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

{
  "staffNum": "20231121",
  "staffCreateDate": "2023-11-21T00:00:00Z",
  "beginDate": "2023-11-21T00:00:00Z",
  "endDate": "2023-11-22T00:00:00Z",
  "staffDetails": [
    {
      "nrPmuDepartId": "1.2.643.5.1.13.13.12.2.31.2855.0.181337",
      "departName": "Централизованная стерилизационная",
      "nrPmuDepartHospitalSubdivisionId": null,
      "hospitalName": null,
      "postFedCode": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "post": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "flCount": 0,
      "averageAge": null,
      "rate": 22.5,
      "busyRate": 2,
      "busyRateMain": 0,
      "externalRate": 0,
      "vacancy": 22.5,
      "staffNote": null
    }
  ]
}

###

DELETE {{url}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###