@FrmoAPI_HostAddress = http://localhost:51005

###

GET {{FrmoAPI_HostAddress}}/health
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/liveness
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org?orgTypeId=1&offset=0&limit=10
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

PUT {{FrmoAPI_HostAddress}}/org?oid=1.2.643.5.1.13.13.12.2.78.6258
Content-Type: application/json

{
    "oid": "1.2.643.5.1.13.13.12.2.78.6258",
    "headOid": null,
    "nameFull": "Частное учреждение образовательная организация высшего образования «Медицинский университет «Реавиз»",
    "nameShort": "Медицинский Университет «Реавиз»",
    "inn": "6317006620",
    "kpp": "631501001",
    "ogrn": "1026301420716",
    "ogrnDate": "2022-03-01T00:00:00Z",
    "legalAddress": {
      "id": 0,
      "aoidArea": "a0548913-da5c-4732-a421-2251d9aed895",
      "aoidStreet": "2fea8389-c6ff-4844-9ec1-67bd10061174",
      "houseid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
      "houseguid": null,
      "GARguid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
      "region": {
        "id": 1,
        "region": "Республика Адыгея (Адыгея)",
        "territoryCode": 1,
        "isFederalCity": false
      },
      "areaName": "Абадзехское",
      "prefixArea": "с/п",
      "streetName": "Песчаная",
      "prefixStreet": "ул",
      "house": "10",
      "building": null,
      "struct": null,
      "flat": null
    },
    "orgType": {
      "code": 1,
      "name": "Государственное юридическое лицо"
    },
    "structure": [],
    "lands": [],
    "parkingArea": 0,
    "certSeries": "12",
    "certNumber": "123456789",
    "certDate": "2022-03-01T00:00:00Z",
    "regOrgName": "Налоговый орган",
    "regDate": "2022-03-01T00:00:00Z",
    "regOrg": "Налоговый орган",
    "regOrgAddress": {
      "id": 0,
      "aoidArea": "bb035cc3-1dc2-4627-9d25-a1bf2d4b936b",
      "aoidStreet": "8bb0d86a-b5d8-4387-ae1b-4a053a6d0760",
      "houseid": "31d1a219-2f5f-4cb9-92e8-9dbace2a668f",
      "houseguid": null,
      "GARguid": "31d1a219-2f5f-4cb9-92e8-9dbace2a668f",
      "region": {
        "id": 63,
        "region": "Самарская область",
        "territoryCode": 63,
        "isFederalCity": false
      },
      "areaName": "Самара",
      "prefixArea": "г",
      "streetName": "Садовая",
      "prefixStreet": "ул",
      "house": "5",
      "building": null,
      "struct": null,
      "flat": null
    },
    "lawFormNameFull": null,
    "moDeptId": {
      "id": 1320705,
      "parentId": 1320700,
      "nameFull": "Федеральная служба по надзору в сфере здравоохранения",
      "nameShort": "Росздравнадзор",
      "isActive": true
    },
    "okopfId": null,
    "founder": null,
    "moAddress": {
      "address": {
        "id": 0,
        "aoidArea": "a0548913-da5c-4732-a421-2251d9aed895",
        "aoidStreet": "2fea8389-c6ff-4844-9ec1-67bd10061174",
        "houseid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
        "houseguid": null,
        "GARguid": "9850bdeb-2009-4539-a8bf-97c5897547f6",
        "region": {
          "id": 1,
          "region": "Республика Адыгея (Адыгея)",
          "territoryCode": 1,
          "isFederalCity": false
        },
        "areaName": "Абадзехское",
        "prefixArea": "с/п",
        "streetName": "Песчаная",
        "prefixStreet": "ул",
        "house": "10",
        "building": null,
        "struct": null,
        "flat": null
      },
      "addrRegion": {
        "code": 1,
        "name": "Республика Адыгея (Адыгея)"
      },
      "cadastralNumber": "12:31:2312312:31",
      "latitude": 44.429867,
      "longitude": 40.252975,
      "postIndex": "123456"
    },
    "deleteDate": "2022-06-27T00:00:00Z",
    "deleteReason": {
      "id": 2,
      "deleteReason": "Дубль карточки МО"
    },
    "regionId": {
      "id": 63,
      "region": "Самарская область",
      "territoryCode": 63,
      "isFederalCity": false
    },
    "medicalSubjectId": [
      {
        "id": 2,
        "medicalSubject": "Медицинская организация"
      }
    ],
    "oldOid": null,
    "moAgencyKindId": {
      "id": 1,
      "parentId": 0,
      "agencyKind": "Больница (в том числе детская)"
    },
    "moAgencyProfileId": null,
    "moTerritoryId": {
      "id": 6,
      "parentId": null
    },
    "moLevelId": {
      "id": 1,
      "moLevel": "I уровень"
    },
    "eoOrganizationType": null,
    "email": "test@test.1.test.ru",
    "site": null,
    "attachedPeople": 0,
    "medicalInformationSystem": false,
    "routingOKS": null,
    "routingNumber": null,
    "primaryVascular": false,
    "medicalAidForm": [],
    "medicalAidCondition": null,
    "maxServiceDistance": 0,
    "mark": null
  }

###

DELETE {{FrmoAPI_HostAddress}}/org?oid=1.2.643.5.1.13.13.12.2.78.6258&deleteReason=1
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/depart?departTypeId=1&oid=1.2.643.5.1.13.13.12.2.31.2855&offset=0&limit=10
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/depart/1.2.643.5.1.13.13.12.2.31.2855.0.385565?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/depart?oid=1.2.643.5.1.13.13.12.2.77.7799
Content-Type: application/json

{
  "departName": "Отделение №1",
  "departStructure": {
    "level": "1",
    "headDepart": "",
  },
  "isPlaned": false
}

###

PUT {{FrmoAPI_HostAddress}}/org/depart?oid=1.2.643.5.1.13.13.12.2.77.7799&entityId=1.2.643.5.1.13.13.12.2.77.7799
Content-Type: application/json

{
  "departName": "Отделение №1",
  "departStructure": {
    "level": "1",
    "headDepart": ""
  },
  "isPlaned": false
}

###

DELETE {{FrmoAPI_HostAddress}}/org/depart?oid=1.2.643.5.1.13.13.12.2.77.7799&entityId=1.2.643.5.1.13.13.12.2.77.7799
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/building/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=47120289-197c-4c8a-b6e4-3806c72bab75
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "rent": false,
  "ownageDocuments": null,
  "lawSubject": null,
  "lawType": null,
  "lawObject": null,
  "cadastralNumber": null,
  "encumbrances": null,
  "lawDescription": null,
  "rentDocuments": null,
  "regDate": null,
  "regNumber": null,
  "landlord": null,
  "renter": null,
  "tenancy": null,
  "capacityVisitors": null,
  "capacityBeds": null,
  "capacityHospital": null,
  "buildName": "Гараж",
  "buildYear": 2023,
  "beginDate": "2023-11-20T00:00:00Z",
  "liquidationDate": null,
  "liquidationReasonId": null,
  "floorCount": 1,
  "hasTrouble": false,
  "troubleDocument": null,
  "buildingPlan": null,
  "cardiologicalDepartments": null,
  "fundament": null,
  "fundamentDescription": null,
  "supportingStructures": null,
  "roofCovering": null,
  "roofCoveringDescription": null,
  "wallsMaterial": null,
  "wallsMaterialDescription": null,
  "ceilingMaterial": null,
  "ceilingMaterialDescription": null,
  "buildingSize": null,
  "rightToUse": null,
  "rightToUseDescription": null,
  "isAdapted": false,
  "isAccesibleEnv": null,
  "isHistorical": false,
  "isWeb": false,
  "buildingArea": 30,
  "builtUpArea": 30,
  "starCost": null,
  "depreciationCost": null,
  "deprecationFactor": null,
  "lastTechnicalSurveyYear": null,
  "lastTechnicalSurveyAct": null,
  "reconstructionYear": null,
  "reconstructionArea": null,
  "troubleActDetails": null,
  "needDestruction": false,
  "destructionDocument": [],
  "destructionDocumentDate": null,
  "destructionDocumentNumber": null,
  "needReconstruction": false,
  "requiredReconstructionArea": null,
  "needRepair": false,
  "repairDocument": [],
  "repairDocumentDate": null,
  "repairDocumentNumber": null,
  "objectTarget": null,
  "objectType": null,
  "floors": [],
  "workPeriod": [],
  "buildingAddress": {
    "addrRegion": "Белгородская область",
    "postIndex": "308007",
    "address": {
      "id": 0,
      "aoidArea": null,
      "aoidStreet": null,
      "houseid": null,
      "houseguid": null,
      "GARguid": "287ef30b-4a63-47f8-be8a-0876c57ab354",
      "region": {
        "id": 31,
        "region": "Белгородская область",
        "territoryCode": 31,
        "isFederalCity": false
      },
      "areaName": "Белгород",
      "prefixArea": null,
      "streetName": "Гагарина",
      "prefixStreet": null,
      "house": "гараж",
      "building": null,
      "struct": null,
      "flat": null
    },
    "cadastralNumber": null,
    "latitude": 50.618652,
    "longitude": 36.580746
  },
  "moTerritorialDepartId": "d344c071-a8d1-4a1b-95b1-7be88dfff906",
  "moTerritorialDepartName": "Кардиохирургический центр"
}

###

PUT {{FrmoAPI_HostAddress}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=47120289-197c-4c8a-b6e4-3806c72bab75
Content-Type: application/json

{
  "rent": false,
  "ownageDocuments": null,
  "lawSubject": null,
  "lawType": null,
  "lawObject": null,
  "cadastralNumber": null,
  "encumbrances": null,
  "lawDescription": null,
  "rentDocuments": null,
  "regDate": null,
  "regNumber": null,
  "landlord": null,
  "renter": null,
  "tenancy": null,
  "capacityVisitors": null,
  "capacityBeds": null,
  "capacityHospital": null,
  "buildName": "Гараж",
  "buildYear": 2023,
  "beginDate": "2023-11-20T00:00:00Z",
  "liquidationDate": null,
  "liquidationReasonId": null,
  "floorCount": 2,
  "hasTrouble": false,
  "troubleDocument": null,
  "buildingPlan": null,
  "cardiologicalDepartments": null,
  "fundament": null,
  "fundamentDescription": null,
  "supportingStructures": null,
  "roofCovering": null,
  "roofCoveringDescription": null,
  "wallsMaterial": null,
  "wallsMaterialDescription": null,
  "ceilingMaterial": null,
  "ceilingMaterialDescription": null,
  "buildingSize": null,
  "rightToUse": null,
  "rightToUseDescription": null,
  "isAdapted": false,
  "isAccesibleEnv": null,
  "isHistorical": false,
  "isWeb": false,
  "buildingArea": 30,
  "builtUpArea": 30,
  "starCost": null,
  "depreciationCost": null,
  "deprecationFactor": null,
  "lastTechnicalSurveyYear": null,
  "lastTechnicalSurveyAct": null,
  "reconstructionYear": null,
  "reconstructionArea": null,
  "troubleActDetails": null,
  "needDestruction": false,
  "destructionDocument": [],
  "destructionDocumentDate": null,
  "destructionDocumentNumber": null,
  "needReconstruction": false,
  "requiredReconstructionArea": null,
  "needRepair": false,
  "repairDocument": [],
  "repairDocumentDate": null,
  "repairDocumentNumber": null,
  "objectTarget": null,
  "objectType": null,
  "floors": [],
  "workPeriod": [],
  "buildingAddress": {
    "addrRegion": "Белгородская область",
    "postIndex": "308007",
    "address": {
      "id": 0,
      "aoidArea": null,
      "aoidStreet": null,
      "houseid": null,
      "houseguid": null,
      "GARguid": "287ef30b-4a63-47f8-be8a-0876c57ab354",
      "region": {
        "id": 31,
        "region": "Белгородская область",
        "territoryCode": 31,
        "isFederalCity": false
      },
      "areaName": "Белгород",
      "prefixArea": null,
      "streetName": "Гагарина",
      "prefixStreet": null,
      "house": "гараж",
      "building": null,
      "struct": null,
      "flat": null
    },
    "cadastralNumber": null,
    "latitude": 50.618652,
    "longitude": 36.580746
  },
  //"moTerritorialDepartId": "d344c071-a8d1-4a1b-95b1-7be88dfff906",
  //"moTerritorialDepartName": "Кардиохирургический центр"
}

###

DELETE {{FrmoAPI_HostAddress}}/org/building?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=47120289-197c-4c8a-b6e4-3806c72bab75
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/tpgg?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/territorialDepart?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/territorialDepart/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=d344c071-a8d1-4a1b-95b1-7be88dfff906
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/territorialDepart?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "moTerritorialDepartName": "Кардиохирургический центр",
  "buildings": [
    {
      "buildingId": "9c5ad425-a60f-440e-a43c-c78c0f4e711f",
      "buildingName": "Кардиохирургический центр"
    },
    {
      "buildingId": "e037d2f6-5998-4ad7-9a24-d7c7ca653e6d",
      "buildingName": "Пансионат"
    }
  ],
  "marks": []
}

###

PUT {{FrmoAPI_HostAddress}}/org/territorialDepart?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=d344c071-a8d1-4a1b-95b1-7be88dfff906
Content-Type: application/json

{
  "moTerritorialDepartName": "Кардиохирургический центр",
  "buildings": [
    {
      "buildingId": "9c5ad425-a60f-440e-a43c-c78c0f4e711f",
      "buildingName": "Кардиохирургический центр"
    },
    {
      "buildingId": "e037d2f6-5998-4ad7-9a24-d7c7ca653e6d",
      "buildingName": "Пансионат"
    }
  ],
  "marks": [
    {
      "code": 1,
      "name": "МО с медицинскими подразделениями"
    }
  ]
}

###

DELETE {{FrmoAPI_HostAddress}}/org/territorialDepart?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=d344c071-a8d1-4a1b-95b1-7be88dfff906
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/airAmbulance?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/airAmbulance/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/airAmbulance?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "airAmbulanceName": "string",
  "depart": {
    "code": "string",
    "name": "string"
  },
  "address": {

    "aoidArea": "string",
    "aoidStreet": "string",
    "houseid": "string",
    "houseguid": "string",
    "GARguid": "string",
    "region": {
      "id": 1,
      "region": "string",
      "territoryCode": 55,
      "isFederalCity": true
    },
    "areaName": "string",
    "prefixArea": "string",
    "streetName": "string",
    "prefixStreet": "string",
    "house": "string",
    "building": "string",
    "struct": "string",
    "flat": "string"
  },
  "addressLatitude": 56.125454,
  "addressLongitude": 56.125454,
  "hasHelicopter": true,
  "nightStart": true,
  "nightStartPossibility": 1,
  "helipadCount": 1,
  "helipadNightStart": 1,
  "weightRestrictions": 1,
  "farHelipadCount": 1,
  "farHelipadNightStart": 1,
  "farHelipadWeightRestrictions": 1,
  "helipadAddresses": [
    {

      "aoidArea": "string",
      "aoidStreet": "string",
      "houseid": "string",
      "houseguid": "string",
      "GARguid": "string",
      "region": {
        "id": 1,
        "region": "string",
        "territoryCode": 55,
        "isFederalCity": true
      },
      "areaName": "string",
      "prefixArea": "string",
      "streetName": "string",
      "prefixStreet": "string",
      "house": "string",
      "building": "string",
      "struct": "string",
      "flat": "string",
      "latitude": 56.125454,
      "longitude": 56.125454
    }
  ],
  "reanimationHelipadCount": 1,
  "nonReanimationHelipadCount": 1,
  "helicopterEquipment": [
    "string"
  ],
  "reanimobileCount": 10,
  "reanimobileAddresses": [
    {
      "aoidArea": "string",
      "aoidStreet": "string",
      "houseid": "string",
      "houseguid": "string",
      "GARguid": "string",
      "region": {
        "id": 1,
        "region": "string",
        "territoryCode": 55,
        "isFederalCity": true
      },
      "areaName": "string",
      "prefixArea": "string",
      "streetName": "string",
      "prefixStreet": "string",
      "house": "string",
      "building": "string",
      "struct": "string",
      "flat": "string",
      "latitude": 56.125454,
      "longitude": 56.125454
    }
  ],
  "reanimobileEquipment": [
    "string"
  ]
}

###

PUT {{FrmoAPI_HostAddress}}/org/airAmbulance?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

{
  "airAmbulanceName": "string",
  "depart": {
    "code": "string",
    "name": "string"
  },
  "address": {

    "aoidArea": "string",
    "aoidStreet": "string",
    "houseid": "string",
    "houseguid": "string",
    "GARguid": "string",
    "region": {
      "id": 1,
      "region": "string",
      "territoryCode": 55,
      "isFederalCity": true
    },
    "areaName": "string",
    "prefixArea": "string",
    "streetName": "string",
    "prefixStreet": "string",
    "house": "string",
    "building": "string",
    "struct": "string",
    "flat": "string"
  },
  "addressLatitude": 56.125454,
  "addressLongitude": 56.125454,
  "hasHelicopter": true,
  "nightStart": true,
  "nightStartPossibility": 1,
  "helipadCount": 1,
  "helipadNightStart": 1,
  "weightRestrictions": 1,
  "farHelipadCount": 1,
  "farHelipadNightStart": 1,
  "farHelipadWeightRestrictions": 1,
  "helipadAddresses": [
    {

      "aoidArea": "string",
      "aoidStreet": "string",
      "houseid": "string",
      "houseguid": "string",
      "GARguid": "string",
      "region": {
        "id": 1,
        "region": "string",
        "territoryCode": 55,
        "isFederalCity": true
      },
      "areaName": "string",
      "prefixArea": "string",
      "streetName": "string",
      "prefixStreet": "string",
      "house": "string",
      "building": "string",
      "struct": "string",
      "flat": "string",
      "latitude": 56.125454,
      "longitude": 56.125454
    }
  ],
  "reanimationHelipadCount": 1,
  "nonReanimationHelipadCount": 1,
  "helicopterEquipment": [
    "string"
  ],
  "reanimobileCount": 10,
  "reanimobileAddresses": [
    {
      "aoidArea": "string",
      "aoidStreet": "string",
      "houseid": "string",
      "houseguid": "string",
      "GARguid": "string",
      "region": {
        "id": 1,
        "region": "string",
        "territoryCode": 55,
        "isFederalCity": true
      },
      "areaName": "string",
      "prefixArea": "string",
      "streetName": "string",
      "prefixStreet": "string",
      "house": "string",
      "building": "string",
      "struct": "string",
      "flat": "string",
      "latitude": 56.125454,
      "longitude": 56.125454
    }
  ],
  "reanimobileEquipment": [
    "string"
  ]
}

###

DELETE {{FrmoAPI_HostAddress}}/org/airAmbulance/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/equipment?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/equipment/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=da897201-bfd0-46ba-b94c-b3a17ba78371
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/equipment?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "building": {
    "buildingId": "9c5ad425-a60f-440e-a43c-c78c0f4e711f",
    "buildingName": "Кардиохирургический центр",
    "floor": [
      {
        "floorId": "67c03e42-81f1-4737-95ff-1a71c55d9eea",
        "floorName": "1 этаж",
        "buildingRoom": [
          {
            "roomId": "5a282eb9-c1a7-4d97-913e-3443d161032d",
            "roomName": "регистратура",
            "roomArea": 0
          }
        ]
      }
    ]
  },
  "depart": {
    "departId": "1.2.643.5.1.13.13.12.2.31.2855.0.276231",
    "departName": "Региональный сосудистый центр для больных с острым коронарным синдромом",
    "subdivision": [],
    "room": []
  },
  "type": "Медицинское оборудование",
  "anotherAddress": null,
  "anotherAddressReason": null,
  "equipmentSection": {
    "code": 26,
    "name": "Устройства систем искусственной вентиляции"
  },
  "equipmentType": {
    "code": 390,
    "name": "216540 Аппарат искусственной вентиляции легких пневматический автоматический, многоразового использования"
  },
  "equipmentName": "Аппарат искусственной вентиляции легких Vela",
  "equipmentTypeId": 0,
  "vendor": "\"Вяирэ Медикал Инк.\"",
  "oksmId": "США",
  "model": "Аппарат искусственной вентиляции легких Vela",
  "registrationCertificate": "ФСЗ 2011/10425",
  "registrationDate": "2020-05-18T00:00:00Z",
  "serialNumber": "AНTO4754",
  "inventoryNumber": "4240016304",
  "productDate": "2020-05-18T00:00:00Z",
  "beginDate": "2020-06-27T00:00:00Z",
  "lifeTime": 7,
  "needReplace": false,
  "isShared": false,
  "count": 1,
  "endDate": null,
  "endReason": null
}

###

PUT {{FrmoAPI_HostAddress}}/org/equipment?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=da897201-bfd0-46ba-b94c-b3a17ba78371
Content-Type: application/json

{
  "building": {
    "buildingId": "9c5ad425-a60f-440e-a43c-c78c0f4e711f",
    "buildingName": "Кардиохирургический центр",
    "floor": [
      {
        "floorId": "67c03e42-81f1-4737-95ff-1a71c55d9eea",
        "floorName": "1 этаж",
        "buildingRoom": [
          {
            "roomId": "5a282eb9-c1a7-4d97-913e-3443d161032d",
            "roomName": "регистратура",
            "roomArea": 0
          }
        ]
      }
    ]
  },
  "depart": {
    "departId": "1.2.643.5.1.13.13.12.2.31.2855.0.276231",
    "departName": "Региональный сосудистый центр для больных с острым коронарным синдромом",
    "subdivision": [],
    "room": []
  },
  "type": "Медицинское оборудование",
  "anotherAddress": null,
  "anotherAddressReason": null,
  "equipmentSection": {
    "code": 26,
    "name": "Устройства систем искусственной вентиляции"
  },
  "equipmentType": {
    "code": 390,
    "name": "216540 Аппарат искусственной вентиляции легких пневматический автоматический, многоразового использования"
  },
  "equipmentName": "Аппарат искусственной вентиляции легких Vela",
  "equipmentTypeId": 0,
  "vendor": "\"Вяирэ Медикал Инк.\"",
  "oksmId": "США",
  "model": "Аппарат искусственной вентиляции легких Vela",
  "registrationCertificate": "ФСЗ 2011/10425",
  "registrationDate": "2020-05-18T00:00:00Z",
  "serialNumber": "AНTO4754",
  "inventoryNumber": "4240016304",
  "productDate": "2020-05-18T00:00:00Z",
  "beginDate": "2020-06-27T00:00:00Z",
  "lifeTime": 7,
  "needReplace": false,
  "isShared": false,
  "count": 1,
  "endDate": null,
  "endReason": null
}

###

DELETE {{FrmoAPI_HostAddress}}/org/equipment?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=da897201-bfd0-46ba-b94c-b3a17ba78371
Content-Type: application/json

###

PUT {{FrmoAPI_HostAddress}}/org/equipment?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

DELETE {{FrmoAPI_HostAddress}}/org/equipment?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/mobileDeparts?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/mobileDeparts/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/mobileDeparts?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "mobileDepartName": "Передвижной ФАП № 1",
  "buildingId": "string",
  "buildingName": "string",
  "departId": "1.2.643.5.1.13.13.12.2.50.4609.0.281",
  "departName": "string",
  "departureCount": 2000,
  "paymentSourceId": {
    "code": 0,
    "name": "string"
  },
  "typeId": {
    "code": 0,
    "name": "string"
  },
  "patientCount": 200,
  "vehicle": [
    {
      "vehicleId": "string",
      "hasRegistrationCertificate": true,
      "registrationCertificate": "string",
      "productYear": "string",
      "beginYear": "string",
      "isForPacient": true,
      "isParamedic": true,
      "ownerOrg": "string",
      "rightToUse": "string",
      "VIN": "string",
      "carMark": "string",
      "carModel": "string",
      "releaseDate": "2019",
      "useDate": "2019-01-01T00:00:00Z",
      "mileage": 10,
      "isNavigation": true,
      "codeNavigation": "string"
    }
  ],
  "addresses": [
    {
      "mobileDepartAddress": {
        "mobileDepartAddressId": "string",
        "GARguid": "string",
        "regionId": 55,
        "latitude": 55.163353,
        "longitude": 37.388834
      }
    }
  ]
}

###

PUT {{FrmoAPI_HostAddress}}/org/mobileDeparts?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

{
  "mobileDepartName": "Передвижной ФАП № 1",
  "buildingId": "string",
  "buildingName": "string",
  "departId": "1.2.643.5.1.13.13.12.2.50.4609.0.281",
  "departName": "string",
  "departureCount": 2000,
  "paymentSourceId": {
    "code": 0,
    "name": "string"
  },
  "typeId": {
    "code": 0,
    "name": "string"
  },
  "patientCount": 200,
  "vehicle": [
    {
      "vehicleId": "string",
      "hasRegistrationCertificate": true,
      "registrationCertificate": "string",
      "productYear": "string",
      "beginYear": "string",
      "isForPacient": true,
      "isParamedic": true,
      "ownerOrg": "string",
      "rightToUse": "string",
      "VIN": "string",
      "carMark": "string",
      "carModel": "string",
      "releaseDate": "2019",
      "useDate": "2019-01-01T00:00:00Z",
      "mileage": 10,
      "isNavigation": true,
      "codeNavigation": "string"
    }
  ],
  "addresses": [
    {
      "mobileDepartAddress": {
        "mobileDepartAddressId": "string",
        "GARguid": "string",
        "regionId": 55,
        "latitude": 55.163353,
        "longitude": 37.388834
      }
    }
  ]
}

###

DELETE {{FrmoAPI_HostAddress}}/org/mobileDeparts?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/houseGround?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/houseGround/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/houseGround?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "houseGround": "Основное",
  "contactPerson": "Иванов",
  "contactPhone": "9051119149",
  "houseGroundAddress": {
    "houseGroundAddressId": "string",
    "postIndex": "234567",
    "address": {

      "aoidArea": "string",
      "aoidStreet": "string",
      "houseid": "string",
      "houseguid": "string",
      "GARguid": "string",
      "region": {
        "id": 1,
        "region": "string",
        "territoryCode": 55,
        "isFederalCity": true
      },
      "areaName": "string",
      "prefixArea": "string",
      "streetName": "string",
      "prefixStreet": "string",
      "house": "string",
      "building": "string",
      "struct": "string",
      "flat": "string"
    },
    "cadastralNumber": "12:34:123456:12",
    "latitude": 52.035497,
    "longitude": 113.496468
  }
}

###

PUT {{FrmoAPI_HostAddress}}/org/houseGround?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

{
  "houseGround": "Основное",
  "contactPerson": "Иванов",
  "contactPhone": "9051119149",
  "houseGroundAddress": {
    "houseGroundAddressId": "string",
    "postIndex": "234567",
    "address": {

      "aoidArea": "string",
      "aoidStreet": "string",
      "houseid": "string",
      "houseguid": "string",
      "GARguid": "string",
      "region": {
        "id": 1,
        "region": "string",
        "territoryCode": 55,
        "isFederalCity": true
      },
      "areaName": "string",
      "prefixArea": "string",
      "streetName": "string",
      "prefixStreet": "string",
      "house": "string",
      "building": "string",
      "struct": "string",
      "flat": "string"
    },
    "cadastralNumber": "12:34:123456:12",
    "latitude": 52.035497,
    "longitude": 113.496468
  }
}

###

DELETE {{FrmoAPI_HostAddress}}/org/houseGround?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/sites?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/sites/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/sites?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "siteName": "string",
  "beginDate": "2021-10-12T20:38:22.914Z",
  "type": {
    "code": 1,
    "name": "string"
  },
  "category": [
    {
      "code": 1,
      "name": "string"
    }
  ],
  "patientAttached": 0,
  "endDate": "2021-10-12T20:38:22.914Z",
  "sitePersons": [
    {
      "sitePersonId": "string",
      "beginDate": "2021-10-12T20:38:22.914Z",
      "endDate": "2021-10-12T20:38:22.914Z",
      "regRoomSingleOid": "string",
      "regRoomOid": "string",
      "regRoomName": "string",
      "personOid": "string",
      "personFio": "string"
    }
  ],
  "siteAddresses": [
    {
      "siteAddressId": "string",
      "address": {
        "addrRegion": "string",
        "postIndex": "string",
        "address": {

          "aoidArea": "string",
          "aoidStreet": "string",
          "houseid": "string",
          "houseguid": "string",
          "region": {
            "id": 1,
            "region": "string",
            "territoryCode": 1,
            "isFederalCity": true
          },
          "areaName": "string",
          "prefixArea": "string",
          "streetName": "string",
          "prefixStreet": "string",
          "house": "string",
          "building": "string",
          "struct": "string",
          "flat": "string"
        },
        "beginDate": "2021-10-12T20:38:22.914Z",
        "endDate": "2021-10-12T20:38:22.914Z"
      }
    }
  ]
}

###

PUT {{FrmoAPI_HostAddress}}/org/sites?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

{
  "siteName": "string",
  "beginDate": "2021-10-12T20:38:22.914Z",
  "type": {
    "code": 1,
    "name": "string"
  },
  "category": [
    {
      "code": 1,
      "name": "string"
    }
  ],
  "patientAttached": 0,
  "endDate": "2021-10-12T20:38:22.914Z",
  "sitePersons": [
    {
      "sitePersonId": "string",
      "beginDate": "2021-10-12T20:38:22.914Z",
      "endDate": "2021-10-12T20:38:22.914Z",
      "regRoomSingleOid": "string",
      "regRoomOid": "string",
      "regRoomName": "string",
      "personOid": "string",
      "personFio": "string"
    }
  ],
  "siteAddresses": [
    {
      "siteAddressId": "string",
      "address": {
        "addrRegion": "string",
        "postIndex": "string",
        "address": {

          "aoidArea": "string",
          "aoidStreet": "string",
          "houseid": "string",
          "houseguid": "string",
          "region": {
            "id": 1,
            "region": "string",
            "territoryCode": 1,
            "isFederalCity": true
          },
          "areaName": "string",
          "prefixArea": "string",
          "streetName": "string",
          "prefixStreet": "string",
          "house": "string",
          "building": "string",
          "struct": "string",
          "flat": "string"
        },
        "beginDate": "2021-10-12T20:38:22.914Z",
        "endDate": "2021-10-12T20:38:22.914Z"
      }
    }
  ]
}

###

DELETE {{FrmoAPI_HostAddress}}/org/sites?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/staff/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

POST {{FrmoAPI_HostAddress}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

{
  "staffNum": "20231121",
  "staffCreateDate": "2023-11-21T00:00:00Z",
  "beginDate": "2023-11-21T00:00:00Z",
  "endDate": "2023-11-22T00:00:00Z",
  "staffDetails": [
    {
      "nrPmuDepartId": "1.2.643.5.1.13.13.12.2.31.2855.0.181337",
      "departName": "Централизованная стерилизационная",
      "nrPmuDepartHospitalSubdivisionId": null,
      "hospitalName": null,
      "postFedCode": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "post": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "flCount": 0,
      "averageAge": null,
      "rate": 22.5,
      "busyRate": 0,
      "busyRateMain": 0,
      "externalRate": 0,
      "vacancy": 22.5,
      "staffNote": null
    }
  ]
}

###

PUT {{FrmoAPI_HostAddress}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

{
  "staffNum": "20231121",
  "staffCreateDate": "2023-11-21T00:00:00Z",
  "beginDate": "2023-11-21T00:00:00Z",
  "endDate": "2023-11-22T00:00:00Z",
  "staffDetails": [
    {
      "nrPmuDepartId": "1.2.643.5.1.13.13.12.2.31.2855.0.181337",
      "departName": "Централизованная стерилизационная",
      "nrPmuDepartHospitalSubdivisionId": null,
      "hospitalName": null,
      "postFedCode": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "post": {
        "code": 173,
        "name": "медицинская сестра стерилизационной "
      },
      "flCount": 0,
      "averageAge": null,
      "rate": 22.5,
      "busyRate": 2,
      "busyRateMain": 0,
      "externalRate": 0,
      "vacancy": 22.5,
      "staffNote": null
    }
  ]
}

###

DELETE {{FrmoAPI_HostAddress}}/org/staff?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=365ee8b2-cf6f-4e0c-a949-f470f17678de
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/licenses?oid=1.2.643.5.1.13.13.12.2.31.2855
Content-Type: application/json

###

GET {{FrmoAPI_HostAddress}}/org/licenses/get?oid=1.2.643.5.1.13.13.12.2.31.2855&entityId=001cd24d-2f93-4060-8cbf-90ff1efeb9af
Content-Type: application/json

###