@url = http://localhost:51003

GET {{url}}/health
Accept: application/json

###

GET {{url}}/liveness
Accept: application/json

###

POST {{url}}/api/v1/pubsub/files
Accept: application/json
Content-Type: application/json

{
    "body": "03693B95-D952-9B85-E063-910A14ACFEBF"
}

###

POST {{url}}/api/v1/pubsub/document-groups
Accept: application/json
Content-Type: application/json

{
    "body": "03693B95-D933-9B85-E063-910A14ACFEBF"
}

###

POST {{url}}/api/v1/pubsub/document-groups/send-to-signing
Accept: application/json
Content-Type: application/json

{
    "body": "03693B95-D933-9B85-E063-910A14ACFEBF"
}

###

POST {{url}}/api/v1/pubsub/route-templates
Accept: application/json
Content-Type: application/json

{
    "body": "03693B95-D933-9B85-E063-910A14ACFEBF"
}

###

POST {{url}}/auto-update-document
Accept: application/json
Content-Type: application/json

###

POST {{url}}/api/v1/pubsub/users/bulk
Accept: application/json
Content-Type: application/json

{
    "body": "2E521581-1F1B-B919-E063-910A14ACBDE0"
}

###

POST {{url}}/api/v1/pubsub/application-types
Accept: application/json
Content-Type: application/json

{
    "body": "03693B95-D933-9B85-E063-910A14ACFEBF"
}

###

POST {{url}}/api/v1/pubsub/document-print-form-file
Accept: application/json
Content-Type: application/json

{
    "body": "43C7336F-EB1B-80C7-E063-910A14AC3C9E"
}

###