kind: ConfigMap
apiVersion: v1
metadata:
  name: healthcheck-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: healthcheck
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://0.0.0.0:80
  HealthChecksUI__HealthChecks__1__Name: Web Proxy
  HealthChecksUI__HealthChecks__1__Uri: http://webproxy/hc
  HealthChecksUI__HealthChecks__2__Name: MGD API
  HealthChecksUI__HealthChecks__2__Uri: http://mgd-api/hc
  HealthChecksUI__HealthChecks__3__Name: BFT eArchive API
  HealthChecksUI__HealthChecks__3__Uri: http://earchive-api/hc
  HealthChecksUI__HealthChecks__4__Name: DaData API
  HealthChecksUI__HealthChecks__4__Uri: http://dadata-api/hc

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: healthcheck
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      service: healthcheck
  template:
    metadata:
      labels:
        app: parusrx
        service: healthcheck
    spec:
      containers:
        - name: healthcheck
          image: pcr.parusnik.org/parusrx/healthcheck:edge
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: healthcheck-cm

---

apiVersion: v1
kind: Service
metadata:
  name: healthcheck
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: healthcheck
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    service: healthcheck