kind: ConfigMap
apiVersion: v1
metadata:
  name: mgd-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: mgd
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  TZ: {{ .Values.db.oracle.tz }}
  Database__Provider: {{ .Values.db.common.provider }}
  Database__ConnectionString: {{ .Values.db.common.connectionString }}
  Urls__Mgd: {{ .Values.mgd.url }}
  Urls__Cipher: {{ .Values.cipher.url }}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: mgd
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: mgd
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mgd
  template:
    metadata:
      labels:
        app: parusrx
        service: mgd
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "mgd-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
    spec:
      containers:
        - name: mgd-api
          image: pcr.parusnik.org/parusrx/mgd-api:edge
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mgd-cm

---

apiVersion: v1
kind: Service
metadata:
  name: mgd-api
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: mgd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
      protocol: TCP
      name: http
  selector:
    service: mgd