kind: ConfigMap
apiVersion: v1
metadata:
  name: webproxy-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: webproxy
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://0.0.0.0:80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: webproxy
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: webproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webproxy
  template:
    metadata:
      labels:
        app: parusrx
        service: webproxy
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "webproxy"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
    spec:
      containers:
        - name: webproxy
          image: pcr.parusnik.org/parusrx/webproxy:edge
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: webproxy-cm

---

apiVersion: v1
kind: Service
metadata:
  name: webproxy
  namespace: {{ .Values.namespace }}
  labels:
    app: parusrx
    service: webproxy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    service: webproxy