## Default Logstash configuration from Logstash Guide.
## from https://www.elastic.co/guide/en/logstash/current/docker-config.html
#
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
pipeline.batch.size: 10000