@url = http://localhost:51002

GET {{url}}/health
Accept: application/json

###

GET {{url}}/liveness
Accept: application/json

###

POST {{url}}/api/v1/suggestions
Content-Type: application/json

{
    "Id": "9E6B79A9-7544-4534-9F51-AE61A80D626C",
    "CreationDate": "2023-05-25T00:00:00",
    "Payload": "BD0D10F5-197C-4676-9D03-61E326B2BEE5"
}

###
