version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  zipkin:
    image: openzipkin/zipkin-slim

  dapr-placement:
    image: "daprio/dapr:1.10.0"

  prx-gateway:
    image: ${REGISTRY:-parusrx}/prx-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateway/Gateway.API/Dockerfile

  prx-gateway-dapr:
    image: "daprio/daprd:1.10.0"
    network_mode: "service:prx-gateway"
    depends_on:
      - prx-gateway

  prx-dadata:
    image: ${REGISTRY:-parusrx}/prx-dadata:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/DaData/DaData.API/Dockerfile

  prx-dadata-dapr:
    image: "daprio/daprd:1.10.0"
    network_mode: "service:prx-dadata"
    depends_on:
      - prx-dadata

  prx-hrlink-employee-role:
    image: ${REGISTRY:-parusrx}/prx-hrlink-employee-role:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/HRLink.EmployeeRole/HRLink.EmployeeRole.API/Dockerfile

  prx-hrlink-employee-role-dapr:
    image: "daprio/daprd:1.10.0"
    network_mode: "service:prx-hrlink-employee-role"
    depends_on:
      - prx-hrlink-employee-role

  prx-hrlink-document-type:
    image: ${REGISTRY:-parusrx}/prx-hrlink-document-type:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/HRLink.DocumentType/HRLink.DocumentType.API/Dockerfile

  prx-hrlink-document-type-dapr:
    image: "daprio/daprd:1.10.0"
    network_mode: "service:prx-hrlink-document-type"
    depends_on:
      - prx-hrlink-document-type