version: '3.7'

services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    ports:
      - "5411:9411"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  prx-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/prx-gateway
    ports:
      - "51001:8080"

  prx-gateway-dapr:
    command: ["./daprd",
      "-app-id", "prx-gateway",
      "-app-port", "8080",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  prx-dadata:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=${ORACLE_TZ:-Europe/Moscow}
      - Database__Provider=${DB_PROVIDER:-Oracle}
      - Database__ConnectionString=${DB_CONNECTION_STRING:-User Id=username;Password=password;Data Source=localhost:1521/meta8561}
      - Urls__Suggestions=${SUGGESTIONS_URL:-https://suggestions.dadata.ru/suggestions/api/4_1/rs}
      - PATH_BASE=/prx-dadata
    ports:
      - "51002:8080"

  prx-dadata-dapr:
    command: ["./daprd",
      "-app-id", "prx-dadata",
      "-app-port", "8080",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  prx-hrlink-employee-role:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=${ORACLE_TZ:-Europe/Moscow}
      - Database__Provider=${DB_PROVIDER:-Oracle}
      - Database__ConnectionString=${DB_CONNECTION_STRING:-User Id=username;Password=password;Data Source=localhost:1521/meta8561}
      - PATH_BASE=/prx-hrlink-employee-roles
    ports:
      - "51003:8080"

  prx-hrlink-employee-role-dapr:
    command: ["./daprd",
      "-app-id", "prx-hrlink-employee-role",
      "-app-port", "8080",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  prx-hrlink-document-type:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=${ORACLE_TZ:-Europe/Moscow}
      - Database__Provider=${DB_PROVIDER:-Oracle}
      - Database__ConnectionString=${DB_CONNECTION_STRING:-User Id=username;Password=password;Data Source=localhost:1521/meta8561}
      - PATH_BASE=/prx-hrlink-document-types
    ports:
      - "51004:8080"

  prx-hrlink-document-type-dapr:
    command: ["./daprd",
      "-app-id", "prx-hrlink-document-type",
      "-app-port", "8080",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"