version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  zipkin:
    image: openzipkin/zipkin-slim

  dapr-placement:
    image: "daprio/dapr:1.10.0"

  gateway:
    image: ${REGISTRY:-parusrx}/gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateway/Gateway.API/Dockerfile

  gateway-dapr:
    image: "daprio/daprd:1.10.0"
    network_mode: "service:gateway"
    depends_on:
      - gateway

  dadata:
    image: ${REGISTRY:-parusrx}/dadata:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/DaData/DaData.API/Dockerfile

  dadata-dapr:
    image: "daprio/daprd:1.10.0"
    network_mode: "service:dadata"
    depends_on:
      - dadata