name: common

on:
  push:
    branches:
      - main
    paths:
      - Common/**
      - .github/workflows/common.yml
  pull_request:
    branches:
      - main
    paths:
      - Common/**
      - .github/workflows/common.yml

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build -c Release src/Common/Common.slnf

      - name: Test
        run: dotnet test -c Release src/Common/Common.slnf
