name: dadata-api

on:
  push:
    branches:
      - main
    paths:
      - src/Common/**
      - src/Services/DaData/**
      - .github/workflows/dadata-api.yml
  pull_request:
    branches:
      - main
    paths:
      - src/Common/**
      - src/Services/DaData/**
      - .github/workflows/dadata-api.yml

env:
  DOTNET_VERSION: '8.0.x'
  REGISTRY_ENDPOINT: docker.io

jobs:
  build-for-pr-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build -c Release src/Services/DaData/DaData.slnf

      - name: Test
        run: dotnet test -c Release src/Services/DaData/DaData.slnf

  build-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build -c Release src/Services/DaData/DaData.slnf

      - name: Test
        run: dotnet test -c Release src/Services/DaData/DaData.slnf

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ ENV.REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Publish
        run: dotnet publish src/Services/DaData/DaData.slnf -r linux-x64 -p PublishProfile=DefaultContainer -p ContainerRegistry=${{ ENV.REGISTRY_ENDPOINT }} -p ContainerImageTag=dev
