name: 'gateway'

on:
  push:
    branches:
      - main
    paths:
      - 'src/Common/**'
      - 'src/ApiGateway/**'
      - '.github/workflows/composite/**'
      - '.github/workflows/gateway.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Common/**'
      - 'src/ApiGateway/**'
      - '.github/workflows/composite/**'
      - '.github/workflows/gateway.yml'

# env:
#   DOTNET_VERSION: '8.0.x'
#   DOTNET_QUALITY: 'preview'
#   PROJECT_PATH: 'src/ApiGateway'
#   TESTS_PATH: 'src/ApiGateway'

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Build and Test
#         uses: ./.github/workflows/composite/build-test
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}
#           dotnet-quality: ${{ env.DOTNET_QUALITY }}
#           project_path: ${{ env.PROJECT_PATH }}
#           tests_path: ${{ env.TESTS_PATH }}

env:
  SERVICE: 'prx-gateway'
  IMAGE_NAME: 'prx-gateway'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-push
        with:
          service: ${{ env.SERVICE }}
          image_name: ${{ env.IMAGE_NAME }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
