name: 'hrlink-employee-roles'

on:
  push:
    branches:
      - main
    paths:
      - 'src/Common/**'
      - 'src/Services/HRlink.EmployeeRoles/**'
      - '.github/workflows/composite/**'
      - '.github/workflows/hrlink-employee-roles.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Common/**'
      - 'src/Services/HRlink.EmployeeRoles/**'
      - '.github/workflows/composite/**'
      - '.github/workflows/hrlink-employee-roles.yml'

env:
  SERVICE: 'prx-hrlink-employee-roles'
  IMAGE_NAME: 'prx-hrlink-employee-roles'

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-push
        with:
          service: ${{ env.SERVICE }}
          image_name: ${{ env.IMAGE_NAME }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
