name: 'sdk'

on:
  push:
    branches:
      - main
    paths:
      - 'src/sdk/**'
      - '.github/workflows/sdk.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/sdk/**'
      - '.github/workflows/sdk.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'
    - name: Restore dependencies
      run: |
        dotnet restore src/sdk/EventBus/src/ParusRX.EventBus.csproj
    - name: Build
      run: |
        dotnet build src/sdk/EventBus/src/ParusRX.EventBus.csproj --configuration Release --no-restore