version: '3.4'

services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    ports:
      - "5411:9411"

  webproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/webproxy
    ports:
      - "8001:80"

  webproxy-dapr:
    command: ["./daprd",
      "-app-id", "webproxy",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  healthcheck:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__1__Name=Web Proxy
      - HealthChecksUI__HealthChecks__1__Uri=http://webproxy/hc
      - HealthChecksUI__HealthChecks__2__Name=MGD API
      - HealthChecksUI__HealthChecks__2__Uri=http://mgd-api/hc
      - HealthChecksUI__HealthChecks__3__Name=BFT eArchive API
      - HealthChecksUI__HealthChecks__3__Uri=http://earchive-api/hc
      - HealthChecksUI__HealthChecks__4__Name=DaData API
      - HealthChecksUI__HealthChecks__4__Uri=http://dadata-api/hc
    ports:
      - "8002:80"

  mgd-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - TZ=${ORACLE_TZ:-Europe/Moscow}
      - Database__Provider=${DB_PROVIDER:-Oracle}
      - Database__ConnectionString=${DB_CONNECTION_STRING:-User Id=username;Password=password;Data Source=localhost:1521/meta8561}
      - Urls__Mgd=${MGD_URL:-http://185.2.32.120:8888/app}
      - Urls__Cipher=${CIPHER_URL:-http://127.0.0.1/cipher}
      - PATH_BASE=/mgd-api
    ports:
      - "8003:80"

  mgd-api-dapr:
    command: ["./daprd",
      "-app-id", "mgd-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  earchive-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - TZ=${ORACLE_TZ:-Europe/Moscow}
      - Database__Provider=${DB_PROVIDER:-Oracle}
      - Database__ConnectionString=${DB_CONNECTION_STRING:-User Id=username;Password=password;Data Source=localhost:1521/meta8561}
      - PATH_BASE=/earchive-api
    ports:
      - "8004:80"

  earchive-api-dapr:
    command: ["./daprd",
      "-app-id", "earchive-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  dadata-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - TZ=${ORACLE_TZ:-Europe/Moscow}
      - Database__Provider=${DB_PROVIDER:-Oracle}
      - Database__ConnectionString=${DB_CONNECTION_STRING:-User Id=username;Password=password;Data Source=localhost:1521/meta8561}
      - Urls__Suggestions=${SUGGESTIONS_URL:-https://suggestions.dadata.ru/suggestions/api/4_1/rs}
      - PATH_BASE=/dadata-api
    ports:
      - "8005:80"

  dadata-api-dapr:
    command: ["./daprd",
      "-app-id", "dadata-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/parusrx-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

